name: Test Push

on:
  push:
    branches:
      - master

permissions:
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Test Dispatch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run test-dispatch.yml --ref dev
          echo "Test Dispatch workflow triggered!"
