name: New Pipeline

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Trigger test dispatch workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run test.yml \
            --repo ${{ github.repository }} \
            --ref dev

          echo "Test Dispatch workflow triggered!"
