# .github/workflows/centralised-pipeline.yml

name: Centralised Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-and-promote:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Centralised pipeline started"
         
